#!/bin/csh 
#
# Stand alone script to launch GPI DRP IDL programs -- for the compiled runtime
#
#


# We need to know the GPI DRP path to invoke the proper scripts to launch the
# GUIs. If that is not already defined as an environment variable, 

if ! $?GPI_DRP_DIR then 
	echo "The environment variable GPI_DRP_DIR must be defined in order to use this script."
	exit
endif


# Colors and sizes of xterms are purely cosmetic, change the below as you desire.

# start the GUIs:
\xterm -bg \#000033 -fg \#CCCC00 -geometry 80x30+20+20  -sb +ls -T 'idl: GPI DRP GUIs' -e idl -rt=$GPI_DRP_DIR/executables/gpi_launch_guis.sav &

# Start the pipeline:
\xterm -bg \#000033 -fg \#FFFFAA -geometry 80x30+20+450 -sb +ls -T 'idl: GPI Pipeline' -e idl -rt=$GPI_DRP_DIR/executables/gpi_launch_pipeline.sav &





