#!/bin/sh
#
# gpiDropDRF
#
# A simple command line script to drop a given DRF file into the GPI Queue. 
#
# The input filename is assumed to be XXXXX.YYY.xml
# The output filename is transformed to XXXXX.waiting.xml in the queue directory
# That directory is set by the environment variable $GPI_QUEUE_DIR
#
# History:
# 2009-06-01  Script written by M. Perrin
# 	      Concept based on osirisDropDRF by Larkin et al.

NEWFN=`echo $1 | sed 's/\..*\.xml/.waiting.xml/'`

cp $1 ${GPI_QUEUE_DIR}/${NEWFN}
echo "${NEWFN} dropped into queue"
