#  Set up environment variables for GPI IFS Software
#	csh/tcsh version
# HISTORY:
#       2010-01-25  Created. M. Perrin
#       2010-02-01  Added IDL_DIR, enclosing quotes - M. Perrin
#       2012-02-02  Split out the data from the software

# *** NOTE** This is the sample file for what the GPI environment
# variables should be. You should copy this file to some different
# filename, e.g.  setenv_GPI_mycomputername.csh, and edit it there. 
# Do NOT edit this file itself to customize it for your computer, 
# since this is under version control and thus your edits would just
# conflict with other users changing this same file too.


#----- Most users will only need to change these next lines? -----

setenv GPI_IFS_DIR "~/GPI"		# base dir for all code
setenv GPI_DATA_DIR "~/GPI/data"	# base dir for all data

setenv GPI_DRP_CONFIG_DIR "~/GPI/my_config"  # where to store my own local config settings? 



#----- Most users will not need to change anything below here -----

# where is the software?
setenv GPI_DRP_DIR "$GPI_IFS_DIR/pipeline"	# pipeline code location
setenv GPI_DRP_TEMPLATES_DIR "$GPI_IFS_DIR/drf_templates"	# pipeline DRF template location

# where is the data?
setenv GPI_RAW_DATA_DIR "$GPI_DATA_ROOT/Detector/"	# where is raw data?
setenv GPI_DRP_OUTPUT_DIR "$GPI_DATA_ROOT/Reduced/"	# where should we put reduced data?
setenv GPI_DRP_QUEUE_DIR "$GPI_DATA_ROOT/queue/"	# where is the DRP Queue directory?
setenv GPI_DRP_LOG_DIR "$GPI_DATA_ROOT/logs/"	# default log dir

#---------- make sure the startup scripts are in your $PATH   -----
setenv PATH "${PATH}:${GPI_DRP_DIR}/scripts"
setenv IDL_PATH "${IDL_PATH}:+${GPI_IFS_DIR}"
